#!/bin/bash
avconv -i $1 -ac 1 -ar 48000 -y tmp.wav
avconv -i $1 -ac 1 -ar 16000 -y tmpa.wav
avconv -i $1 -ac 1 -ar 24000 -y tmpb.wav

echo Alpha - Yw
pocketsphinx_continuous -debug 0 -samprate 16000 -nfft 512 -infile tmpa.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-I/12_und_1_Paar_Augen-$2-Phantom_I.txt

echo Alpha - Yo
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-II/12_und_1_Paar_Augen-$2-Phantom_II.txt

echo Alpha - Yoda
pocketsphinx_continuous -samprate 24000 -nfft 1024 -infile tmpb.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-III/12_und_1_Paar_Augen-$2-Phantom_III.txt


echo Alpha - I
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-IV/12_und_1_Paar_Augen-$2-Phantom_IV.txt

echo Alpha - II
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_3000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-V/12_und_1_Paar_Augen-$2-Phantom_V.txt

echo Alpha - III
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_3000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict wba.dict \
    -lm etc/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-VI/12_und_1_Paar_Augen-$2-Phantom_VI.txt

echo Alpha - IV
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_4000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict wba.dict \
    -lm etc/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-VII/12_und_1_Paar_Augen-$2-Phantom_VII.txt

echo Alpha - V
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict test.dict \
    -lm etc/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-VIII/12_und_1_Paar_Augen-$2-Phantom_VIII.txt

echo Omega - I
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-IX/12_und_1_Paar_Augen-$2-Phantom_IX.txt

echo Omega - II
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_3000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict multi.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-X/12_und_1_Paar_Augen-$2-Phantom_X.txt

echo Omega - III
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_3000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict wba.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-XI/12_und_1_Paar_Augen-$2-Phantom_XI.txt

echo Omega - IV
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/voxforge.cd_cont_4000 \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict test.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-XII/12_und_1_Paar_Augen-$2-Phantom_XII.txt

echo Omega - V
pocketsphinx_continuous -samprate 48000 -nfft 2048 -infile tmp.wav \
    -hmm model_parameters/mein \
    -lw 21 -feat 1s_c_d_dd -beam 1e-40 -wbeam 1e-40 \
    -dict wba.dict \
    -lm etc1/voxforge.lm.DMP \
    -wip 0.000133333333333 \
    -agc none -varnorm no -cmn current 2>/dev/null | tee ../WiW/Phantom-XIII/12_und_1_Paar_Augen-$2-Phantom_XIII.txt
